"""empty message

Revision ID: 54f02b5ec027
Revises: ef588713de71
Create Date: 2026-01-09 18:24:35.117382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f02b5ec027'
down_revision: Union[str, Sequence[str], None] = 'ef588713de71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_number')
    op.add_column('products', sa.Column('rows', sa.Integer(), nullable=False))
    op.drop_column('products', 'columns')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('columns', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('products', 'rows')
    op.add_column('orders', sa.Column('order_number', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
