"""empty message

Revision ID: c44f17d89038
Revises: 36fad9401b95
Create Date: 2026-01-07 15:32:56.515729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'c44f17d89038'
down_revision: Union[str, Sequence[str], None] = '36fad9401b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='usertype',
        new_values=['OWNER', 'USER'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='usertype',
        new_values=['OWNER', 'EMPLOYEE', 'USER'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
