"""empty message

Revision ID: ef588713de71
Revises: e31f784e5da2
Create Date: 2026-01-09 14:22:28.326526

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ef588713de71"
down_revision: Union[str, Sequence[str], None] = "e31f784e5da2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "ORDER_CONFIRMED",
        "ACCEPTED_BY_VENDOR",
        "OUT_FOR_DELIVERY",
        "CANCELLED",
        "CUSTOMER_NOT_AVAILABLE",
        "REJECTED",
        name="orderstatus",
    ).create(op.get_bind())
    sa.Enum(
        "PENDING", "CASH_ON_DELIVERY", "PAID", "FAILED", name="paymentstatus"
    ).create(op.get_bind())
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("order_number", sa.Uuid(), nullable=True),
        sa.Column(
            "payment_status",
            postgresql.ENUM(
                "PENDING",
                "CASH_ON_DELIVERY",
                "PAID",
                "FAILED",
                name="paymentstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "order_status",
            postgresql.ENUM(
                "ORDER_CONFIRMED",
                "ACCEPTED_BY_VENDOR",
                "OUT_FOR_DELIVERY",
                "CANCELLED",
                "CUSTOMER_NOT_AVAILABLE",
                "REJECTED",
                name="orderstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_table(
        "order_products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_products_id"), "order_products", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_products_id"), table_name="order_products")
    op.drop_table("order_products")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    sa.Enum("PENDING", "CASH_ON_DELIVERY", "PAID", "FAILED", name="paymentstatus").drop(
        op.get_bind()
    )
    sa.Enum(
        "ORDER_CONFIRMED",
        "ACCEPTED_BY_VENDOR",
        "OUT_FOR_DELIVERY",
        "CANCELLED",
        "CUSTOMER_NOT_AVAILABLE",
        "REJECTED",
        name="orderstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
