"""empty message

Revision ID: f2a39ac749be
Revises: 328e4ef41382
Create Date: 2026-01-09 11:22:06.797133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a39ac749be'
down_revision: Union[str, Sequence[str], None] = '328e4ef41382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.String(), nullable=True))
    op.add_column('products', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('columns', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'columns')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
